# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#       - FIREBASE_API_KEY=${FIREBASE_API_KEY}
#       - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
#       - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
#       - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
#       - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
#       - FIREBASE_APP_ID=${FIREBASE_APP_ID}
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#     command: >
#       sh -c "
#         npx prisma migrate dev --name init &&
#         npx prisma generate &&
#         npm run dev
#       "

#   db:
#     image: postgres:14-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=docker
#       - POSTGRES_PASSWORD=docker
#       - POSTGRES_DB=docker
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@example.com
#       - PGADMIN_DEFAULT_PASSWORD=admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db

# volumes:
#   postgres_data:

# //////////////////////////////////////////////////////////////////////////////////////

# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#       - FIREBASE_API_KEY=${FIREBASE_API_KEY}
#       - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
#       - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
#       - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
#       - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
#       - FIREBASE_APP_ID=${FIREBASE_APP_ID}
#     volumes:
#       - .:/app
#     command: >
#       sh -c "
#         npx prisma migrate deploy &&
#         npx prisma generate &&
#         npm run dev
#       "

# ////////////////////// Deployment Configuration //////////////////////

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
    restart: always
